# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  
  - name: News
    url: post
    weight: 30
  # - name: Events
  #   url: event
  #   weight: 40
  - name: Research
    url: publication
    weight: 10

  # producct
  - name: Product
    identifier: product
    weight: 20
  - name: Text2Music
    parent: product
    url: https://app.memomind.cn/text2music/
    weight: 1
  - name: test-app
    parent: product
    url: https://app.memomind.cn/test_app/
    weight: 2

  # About
  - name: About
    identifier: about
    weight: 40
  - name: Contact
    parent: about
    url: contact
    weight: 30
  - name: Tour
    parent: about
    url: tour
    weight: 10
  - name: People
    parent: about
    url: people
    weight: 20